import { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { createClient } from '@supabase/supabase-js'
import { Camera, Check, Folder, FolderPlus, Heart, ImagePlus, Lock, LogOut, Mail, MoreHorizontal, Palette, Plus, Settings, ShieldCheck, Upload, UserRound, X } from 'lucide-react'
import './style.css'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY
const supabase = supabaseUrl && supabaseKey && supabaseUrl.includes('.supabase.co') ? createClient(supabaseUrl, supabaseKey) : null
const appUrl = (import.meta.env.VITE_APP_URL || window.location.origin).replace(/\/$/, '')
const backgrounds = ['#F4E4DC','#E3EEDF','#E3EDF3','#F2E7CF','#EBE1EE','#DCE9E6','#F1E3DC','#E8ECD5','#E4E2F3','#F1DFDF','#DCE7F0','#EEE7D9']
const exampleImages = ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=80','https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=80']

const score = password => [password.length >= 8, /[A-ZА-Я]/.test(password), /\d/.test(password), /[^A-Za-zА-Яа-я0-9]/.test(password)].filter(Boolean).length
function Field({ label, children }) { return <label className="field"><span>{label}</span>{children}</label> }
function Logo() { return <div className="logo"><span><Heart size={16} fill="currentColor"/></span> альбом<b>.com</b></div> }
function messageFrom(error) { if (error?.message?.toLowerCase().includes('rate limit')) return 'Слишком много писем за короткое время. Подождите несколько минут. Для реального сайта подключите SMTP — инструкция есть в README.'; return error?.message || 'Не удалось выполнить действие. Попробуйте ещё раз.' }

function App() {
  const [session, setSession] = useState(null)
  const [ready, setReady] = useState(!supabase)
  const [profile, setProfile] = useState(null)
  const [albums, setAlbums] = useState([])
  const [active, setActive] = useState(null)
  const [page, setPage] = useState('home')
  const [modal, setModal] = useState(null)
  const [toast, setToast] = useState(null)
  const slug = window.location.pathname.match(/^\/a\/([^/]+)$/)?.[1]
  const notify = (text, type = 'error') => setToast({ text, type })

  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({data}) => { setSession(data.session); setReady(true) }); const {data} = supabase.auth.onAuthStateChange((_event,next) => setSession(next)); return () => data.subscription.unsubscribe() }, [])
  useEffect(() => { if (!session) { setProfile(null); setAlbums([]); setActive(null); setPage('home'); return }
    const load = async () => { const user = session.user; const [{data: userProfile}, {data, error}] = await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).maybeSingle(), supabase.from('albums').select('id,title,slug,background,created_at,album_folders(id),media(id)').eq('owner_id',user.id).order('created_at',{ascending:false})]); if (error) notify(messageFrom(error)); setProfile(userProfile || { display_name:user.user_metadata.full_name || '', avatar_path:null }); setAlbums(data || []); setActive(current => current?.owner_id === user.id ? current : data?.[0] || null) }; load() }, [session])
  useEffect(() => { if (!session) return; const pending = sessionStorage.getItem('album-invite'); if (!pending) return; const {password, sharedSlug} = JSON.parse(pending); supabase.rpc('unlock_album',{album_slug:sharedSlug,album_password:password}).then(({data,error}) => { if(error) notify(messageFrom(error)); else { setActive(data); sessionStorage.removeItem('album-invite'); window.history.replaceState({},'', '/'); setPage('home') } }) }, [session])

  if (!supabase) return <Setup />
  if (!ready) return <main className="loading"><Logo/><span>Открываем воспоминания…</span></main>
  if (window.location.pathname === '/reset-password') return <Auth initial="new-password" />
  if (slug) return <Invite slug={slug} />
  if (!session) return <Auth />
  const user = session.user
  return <div className="app"><Header user={user} profile={profile} onHome={() => setPage('home')} onProfile={() => setPage('profile')} />{toast && <Toast {...toast} close={() => setToast(null)}/>} {page === 'home' ? <AlbumPage album={active} user={user} openCreate={() => setModal('create-album')} openFolder={folder => setModal({type:'folder',folder})} openUpload={() => setModal({type:'upload',folder:null})} openFolderCreate={() => setModal('create-folder')} openProfile={() => setPage('profile')} /> : <Dashboard user={user} profile={profile} albums={albums} openHome={() => setPage('home')} choose={album => {setActive(album);setPage('home')}} create={() => setModal('create-album')} settings={() => setModal('settings')} />}{modal && <Modal close={() => setModal(null)}>{modal === 'create-album' && <CreateAlbum done={album => {setAlbums(old => [album,...old]);setActive(album);setModal({type:'share',album})}} notify={notify}/>} {modal?.type === 'share' && <Share album={modal.album} close={() => setModal(null)}/>} {modal?.type === 'folder' && <FolderModal folder={modal.folder} album={active} user={user} notify={notify}/>} {modal?.type === 'upload' && <UploadModal album={active} folder={modal.folder} user={user} notify={notify}/>} {modal === 'create-folder' && <CreateFolder album={active} notify={notify} close={() => setModal(null)}/>} {modal === 'settings' && <SettingsModal user={user} profile={profile} notify={notify} close={() => setModal(null)}/>}</Modal>}</div>
}

function Setup() { return <main className="auth-layout"><section className="auth-box"><Logo/><p className="eyebrow">ПЕРВЫЙ ЗАПУСК</p><h1>Подключите Supabase</h1><p>Добавьте адрес проекта и публичный ключ в файл <code>.env</code>, затем перезапустите сайт.</p><pre>VITE_SUPABASE_URL=https://xxxx.supabase.co{`\n`}VITE_SUPABASE_ANON_KEY=ваш_публичный_ключ</pre></section></main> }
function Header({user,profile,onHome,onProfile}) { const initial = (profile?.display_name || user.email).slice(0,1).toUpperCase(); return <header><button onClick={onHome}><Logo/></button><div className="header-actions"><span className="mail"><Mail size={15}/>{user.email}<i>Проверен</i></span><button className="avatar" onClick={onProfile}>{profile?.avatar_path ? <SignedAvatar path={profile.avatar_path}/> : initial}</button></div></header> }

function Auth({initial='login'}) { const [mode,setMode]=useState(initial),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[status,setStatus]=useState(null),[busy,setBusy]=useState(false); const submit=async event=>{event.preventDefault();setBusy(true);setStatus(null);let error; if(mode==='login')({error}=await supabase.auth.signInWithPassword({email,password})); if(mode==='signup')({error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:appUrl}})); if(mode==='reset')({error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${appUrl}/reset-password`})); if(mode==='new-password')({error}=await supabase.auth.updateUser({password}));setBusy(false);if(error)return setStatus({type:'error',text:messageFrom(error)});if(mode==='signup')setStatus({type:'success',text:'Письмо с подтверждением отправлено. Откройте его, затем войдите в аккаунт.'});if(mode==='reset')setStatus({type:'success',text:'Ссылка для сброса отправлена на почту. Проверьте также папку «Спам».'});if(mode==='new-password'){window.history.replaceState({},'', '/');window.location.reload()} }; const titles={login:'С возвращением',signup:'Создайте свой альбом',reset:'Сброс пароля','new-password':'Новый пароль'};return <main className="auth-layout"><section className="auth-visual"><div className="visual-image"/><p>Храните самые дорогие<br/><i>моменты вместе.</i></p></section><section className="auth-box"><Logo/><p className="eyebrow">СЕМЕЙНЫЕ ВОСПОМИНАНИЯ</p><h1>{titles[mode]}</h1><p>{mode==='reset'?'Мы отправим стандартную безопасную ссылку для сброса пароля.':mode==='new-password'?'Введите и сохраните новый пароль.':'Ваше личное пространство для семейных историй.'}</p><form onSubmit={submit}>{mode!=='new-password'&&<Field label="Электронная почта"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></Field>}{['login','signup','new-password'].includes(mode)&&<Field label={mode==='new-password'?'Новый пароль':'Пароль'}><input required minLength="6" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Минимум 6 символов"/></Field>}{status&&<p className={`form-message ${status.type}`}>{status.text}</p>}<button className="primary" disabled={busy}>{busy?'Пожалуйста, подождите…':mode==='login'?'Войти':mode==='signup'?'Создать аккаунт':mode==='reset'?'Отправить ссылку':'Сохранить пароль'}</button></form><div className="auth-links">{mode==='login'&&<><button onClick={()=>setMode('reset')}>Забыли пароль?</button><span>Нет аккаунта? <button onClick={()=>setMode('signup')}>Зарегистрироваться</button></span></>}{mode==='signup'&&<span>Уже есть аккаунт? <button onClick={()=>setMode('login')}>Войти</button></span>}{mode==='reset'&&<button onClick={()=>setMode('login')}>Вернуться ко входу</button>}</div></section></main> }
function Invite({slug}) { const [password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);const {data,error}=await supabase.rpc('check_album_password',{album_slug:slug,album_password:password});setBusy(false);if(error||!data)return setMessage('Пароль неверный или эта ссылка не существует.');sessionStorage.setItem('album-invite',JSON.stringify({sharedSlug:slug,password}));window.location.href='/'};return <main className="auth-layout"><section className="auth-box invite"><Logo/><p className="eyebrow">ВАС ПРИГЛАСИЛИ</p><h1>Семейный альбом</h1><p>Этот альбом защищён. Введите пароль, после чего войдите или зарегистрируйтесь.</p><form onSubmit={submit}><Field label="Пароль альбома"><input autoFocus required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Введите пароль"/></Field>{message&&<p className="form-message error">{message}</p>}<button className="primary" disabled={busy}><Lock size={16}/>{busy?'Проверяем…':'Продолжить'}</button></form></section></main> }

function AlbumPage({album,user,openCreate,openFolder,openUpload,openFolderCreate,openProfile}) { const [folders,setFolders]=useState([]),[media,setMedia]=useState([]);useEffect(()=>{if(!album)return;Promise.all([supabase.from('album_folders').select('*').eq('album_id',album.id).order('created_at'),supabase.from('media').select('*').eq('album_id',album.id).is('folder_id',null).order('created_at',{ascending:false})]).then(([folderResult,mediaResult])=>{setFolders(folderResult.data||[]);setMedia(mediaResult.data||[])})},[album]);const visualMedia=media.filter(x=>x.media_type==='image').slice(0,5);return <>{!album?<EmptyStart create={openCreate}/>:<><section className="album-hero" style={{background:album.background}}><p className="eyebrow">✦ СЕМЕЙНАЯ ИСТОРИЯ ✦</p><h1>{album.title}</h1><p>Место, в котором живут самые тёплые воспоминания.</p><div className="slideshow">{visualMedia.length?visualMedia.map(item=><SignedImage key={item.id} path={item.file_path}/>):exampleImages.map((src,index)=><figure key={src}><img src={src} alt="Пример фотографии"/><figcaption>{index===1?'Пример':'Пример'}</figcaption></figure>)}</div></section><section className="content"><div className="section-heading"><div><p className="eyebrow">ВСЕ ВОСПОМИНАНИЯ</p><h2>Фотографии и папки</h2></div><button className="secondary" onClick={openProfile}>Личный кабинет →</button></div><div className="quick-actions"><button onClick={openUpload}><ImagePlus size={18}/><span>Добавить<br/><b>фото или видео</b></span></button><button onClick={openFolderCreate}><FolderPlus size={18}/><span>Создать<br/><b>новую папку</b></span></button></div>{media.length>0&&<section><h3 className="subheading">Без папки</h3><MediaGrid items={media}/></section>}{folders.length>0&&<section><h3 className="subheading">Папки</h3><div className="folder-grid">{folders.map(folder=><button className="folder-card" key={folder.id} onClick={()=>openFolder(folder)}><div className="folder-cover" style={{background:folder.color}}><Folder size={42}/></div><b>{folder.name}</b><small>Открыть папку</small></button>)}</div></section>}</section></>}</> }
function EmptyStart({create}) { return <main className="empty-start"><div><Logo/><p className="eyebrow">ВАШЕ ПРОСТРАНСТВО</p><h1>Начните семейную историю</h1><p>Создайте защищённый альбом, загрузите любимые фотографии и поделитесь ссылкой только с близкими.</p><button className="primary" onClick={create}><Plus size={17}/>Создать первый альбом</button></div><div className="starter-art"><img src={exampleImages[2]} alt="Море и скалы"/><span>Ваши воспоминания<br/>начнутся здесь</span></div></main> }
function MediaGrid({items}) { return <div className="media-grid">{items.map(item=>item.media_type==='image'?<SignedImage key={item.id} path={item.file_path}/>:<div className="video-card" key={item.id}>Видео</div>)}</div> }
function SignedImage({path}) { const [src,setSrc]=useState('');useEffect(()=>{if(path?.startsWith('http'))setSrc(path);else supabase.storage.from('album-media').createSignedUrl(path,3600).then(({data})=>setSrc(data?.signedUrl||''))},[path]);return src?<img src={src} alt="Воспоминание"/>:<div className="image-placeholder"/> }

function Dashboard({user,profile,albums,openHome,choose,create,settings}) { const logout=()=>supabase.auth.signOut();return <main className="dashboard"><aside><button className="back" onClick={openHome}>← Вернуться к альбому</button><div className="user-card"><span className="avatar large">{profile?.avatar_path?<SignedAvatar path={profile.avatar_path}/>:<UserRound size={19}/>}</span><div><b>{profile?.display_name||'Без имени'}</b><small>{user.email}</small></div></div><nav><button className="active"><Heart size={16}/>Мои альбомы</button><button onClick={settings}><Settings size={16}/>Настройки профиля</button></nav><div className="side-bottom"><button className="primary" onClick={create}><Plus size={17}/>Создать альбом</button><button className="logout" onClick={logout}><LogOut size={16}/>Выйти из аккаунта</button></div></aside><section className="dashboard-content"><div className="dashboard-banner"><div><p className="eyebrow">ЛИЧНЫЙ КАБИНЕТ</p><h1>Здравствуйте, {profile?.display_name||'друг'}!</h1><p>Здесь собраны только ваши личные альбомы.</p></div><button className="primary" onClick={create}><Plus size={17}/>Новый альбом</button></div><div className="stats"><div><b>{albums.length}</b><span>альбомов</span></div><div><b>{albums.reduce((sum,album)=>sum+(album.album_folders?.length||0),0)}</b><span>папок</span></div><div><b><ShieldCheck size={17}/></b><span>приватный доступ</span></div></div><h2>Мои альбомы</h2>{albums.length?<div className="album-list">{albums.map(album=><article key={album.id}><div className="album-swatch" style={{background:album.background}}><Heart size={21} fill="currentColor"/></div><section><small><Lock size={11}/>Защищён паролем</small><h3>{album.title}</h3><p>{album.album_folders?.length||0} папок · {album.media?.length||0} файлов без папки</p><button onClick={()=>choose(album)}>Открыть альбом →</button></section><MoreHorizontal size={18}/></article>)}</div>:<div className="empty-card"><Heart size={28}/><h3>Здесь появятся ваши альбомы</h3><p>Чужие альбомы не отображаются, пока их ссылкой и паролем не поделились с вами.</p></div>}</section></main> }
function SignedAvatar({path}) { const [src,setSrc]=useState('');useEffect(()=>{supabase.storage.from('avatars').createSignedUrl(path,3600).then(({data})=>setSrc(data?.signedUrl||''))},[path]);return src?<img src={src} alt="Аватар"/>:<UserRound size={19}/> }

function Modal({children,close}) { return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X size={19}/></button>{children}</section></div> }
function CreateAlbum({done,notify}) { const [title,setTitle]=useState(''),[password,setPassword]=useState(''),[background,setBackground]=useState(backgrounds[0]),[busy,setBusy]=useState(false);const level=score(password);const submit=async e=>{e.preventDefault();setBusy(true);const slug=`${title.toLowerCase().trim().replace(/[^a-zа-я0-9]+/gi,'-').replace(/(^-|-$)/g,'')}-${crypto.randomUUID().slice(0,8)}`;const {data,error}=await supabase.rpc('create_album',{album_title:title,album_slug:slug,album_password:password,album_background:background});setBusy(false);if(error)return notify(messageFrom(error));done(data)};return <form onSubmit={submit}><p className="eyebrow">НОВЫЙ АЛЬБОМ</p><h2>Сохраните историю</h2><Field label="Название альбома"><input required maxLength="100" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Например, Семья Ивановых"/></Field><Field label="Пароль для гостей"><input required minLength="8" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Не менее 8 символов"/></Field><div className="meter"><div>{[1,2,3,4].map(x=><i key={x} className={level>=x?'on':''}/>)}</div><span>{['Введите пароль','Слабый пароль','Нормальный пароль','Хороший пароль','Надёжный пароль'][level]}</span></div><p className="field-label">Выберите фон</p><div className="backgrounds">{backgrounds.map(color=><button type="button" aria-label="Выбрать фон" key={color} style={{background:color}} className={background===color?'chosen':''} onClick={()=>setBackground(color)}/>)}</div><button className="primary" disabled={busy||level<2}>{busy?'Создаём…':'Создать альбом'}</button></form> }
function CreateFolder({album,notify,close}) { const [name,setName]=useState(''),[color,setColor]=useState('#DCE9E3'),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);const {error}=await supabase.from('album_folders').insert({album_id:album.id,name:name.trim(),color});setBusy(false);if(error)return notify(messageFrom(error));notify('Папка создана.','success');close()};return <form onSubmit={submit}><p className="eyebrow">НОВАЯ ПАПКА</p><h2>Соберите воспоминания</h2><Field label="Название папки"><input required autoFocus maxLength="100" value={name} onChange={e=>setName(e.target.value)} placeholder="Например, Море 2025"/></Field><Field label="Цвет папки"><div className="color-row"><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><span>Выберите любой цвет из палитры</span></div></Field><button className="primary" disabled={busy}>{busy?'Создаём…':'Создать папку'}</button></form> }
function Share({album,close}) { const link=`${appUrl}/a/${album.slug}`;return <div className="share-modal"><span className="success"><Check size={25}/></span><p className="eyebrow">АЛЬБОМ ГОТОВ</p><h2>Отправьте ссылку близким</h2><p>Ссылка бессрочная. Гость сможет войти только после ввода пароля альбома и авторизации.</p><div className="share-link"><a href={link} target="_blank" rel="noreferrer">{link}</a><button onClick={()=>navigator.clipboard.writeText(link)}>Копировать</button></div><button className="primary" onClick={close}>Понятно</button></div> }
function FolderModal({folder,album,user,notify}) { const [name,setName]=useState(folder.name),[color,setColor]=useState(folder.color),[files,setFiles]=useState([]),[saving,setSaving]=useState(false);useEffect(()=>{supabase.from('media').select('*').eq('folder_id',folder.id).order('created_at',{ascending:false}).then(({data})=>setFiles(data||[]))},[folder.id]);const save=async()=>{setSaving(true);const {error}=await supabase.from('album_folders').update({name,color}).eq('id',folder.id);setSaving(false);if(error)notify(messageFrom(error));else notify('Папка сохранена.','success')};return <div><p className="eyebrow">ПАПКА АЛЬБОМА</p><h2>Настройки и файлы</h2><Field label="Название"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Цвет папки"><div className="color-row"><input aria-label="Цвет папки" type="color" value={color} onChange={e=>setColor(e.target.value)}/><span>Выберите любой цвет в палитре</span></div></Field><button className="secondary save-folder" onClick={save} disabled={saving}><Palette size={15}/>{saving?'Сохраняем…':'Сохранить папку'}</button><MediaGrid items={files}/><UploadModal album={album} folder={folder} user={user} notify={notify} onUploaded={items=>setFiles(old=>[...items,...old])}/></div> }
function UploadModal({album,folder,user,notify,onUploaded}) { const input=useRef(null),[busy,setBusy]=useState(false),[count,setCount]=useState(0);const upload=async e=>{const picked=Array.from(e.target.files||[]).slice(0,35);if(!picked.length)return;setBusy(true);setCount(picked.length);const added=[];for(const file of picked){const safe=file.name.replace(/[^a-zA-Zа-яА-Я0-9._-]/g,'_');const path=`${user.id}/${album.id}/${folder?.id||'direct'}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from('album-media').upload(path,file);if(uploadError){setBusy(false);return notify(messageFrom(uploadError))}const {data,error}=await supabase.from('media').insert({album_id:album.id,folder_id:folder?.id||null,file_path:path,media_type:file.type.startsWith('video/')?'video':'image'}).select().single();if(error){setBusy(false);return notify(messageFrom(error))}added.push(data)}setBusy(false);notify(`${added.length} файлов добавлено.`,'success');onUploaded?.(added)};return <div className="upload-area"><input ref={input} hidden type="file" accept="image/*,video/*" multiple onChange={upload}/><button onClick={()=>input.current.click()} disabled={busy}><Upload size={19}/><b>{busy?`Загружаем ${count} файлов…`:'Добавить фото или видео'}</b><span>До 35 файлов за одну загрузку</span></button></div> }
function SettingsModal({user,profile,notify,close}) { const [name,setName]=useState(profile?.display_name||''),[avatar,setAvatar]=useState(profile?.avatar_path||null),[busy,setBusy]=useState(false);const file=useRef(null);const save=async e=>{e.preventDefault();setBusy(true);const {error}=await supabase.from('profiles').upsert({id:user.id,display_name:name.trim(),avatar_path:avatar});setBusy(false);if(error)return notify(messageFrom(error));notify('Профиль сохранён.','success');close()};const upload=async e=>{const image=e.target.files?.[0];if(!image)return;setBusy(true);const path=`${user.id}/${crypto.randomUUID()}-${image.name}`;const {error}=await supabase.storage.from('avatars').upload(path,image);setBusy(false);if(error)return notify(messageFrom(error));setAvatar(path)};return <form onSubmit={save}><p className="eyebrow">НАСТРОЙКИ ПРОФИЛЯ</p><h2>Личные данные</h2><div className="avatar-editor"><span className="avatar huge">{avatar?<SignedAvatar path={avatar}/>:<UserRound size={28}/>}</span><button type="button" className="secondary" onClick={()=>file.current.click()}><Camera size={16}/>Изменить аватар</button><input hidden ref={file} type="file" accept="image/*" onChange={upload}/></div><Field label="Ваше имя"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Например, Ирина"/></Field><Field label="Электронная почта"><input disabled value={user.email}/></Field><button className="primary" disabled={busy}>{busy?'Сохраняем…':'Сохранить изменения'}</button></form> }
function Toast({text,type,close}) { return <div className={`toast ${type}`}><span>{text}</span><button onClick={close}><X size={16}/></button></div> }
createRoot(document.getElementById('root')).render(<App/>)
